In [1]:
from pathlib import Path
import sys

import pandas as pd


PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

SRC_DIR = PROJECT_ROOT / "src"

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

TRAIN_DIR = PROJECT_ROOT / "data" / "train"

print("Project root:", PROJECT_ROOT)

Project root: /Users/ankitraj/Desktop/Amazon_Ml_challenge26

In [2]:
from business_entity_resol.io.reader import read_source_file
from business_entity_resol.preprocessing.normalization import (
    normalize_dataframe,
)

In [3]:
train_source1 = read_source_file(
    TRAIN_DIR / "train_source1.tsv"
)

print(train_source1.shape)

(2206821, 4)

In [4]:
sample = train_source1.sample(
    n=1000,
    random_state=42,
)

sample.head()

,entity_id,business_name,business_address,country
2195840,S1-53356671,Pediatric Medicine PLLC,"4850 20, Otisco, NY",US
1487051,S1-320151505,Fetech National Twin,"19034 Woodburn Road, Woodburn, IN",US
1878277,S1-938947364,General Design Innovations LLC,"7241 Osage Avenue, Mesa, AZ",US
993966,S1-195839862,Construction Ideaz Papers Private Limited,"Building No.4/606, Prabhul Cottage Karimbalur,...",India
565428,S1-655046555,Penaloza and Bittle First Inc.,"4255 Charleswood Avenue, Memphis, TN",US

In [5]:
normalized_sample = normalize_dataframe(sample)

print(normalized_sample.shape)
normalized_sample.head()

(1000, 13)

,entity_id,business_name,business_address,country,name_raw,name_norm,name_compact,name_tokens,address_raw,address_norm,address_compact,address_tokens,address_numbers
0,S1-53356671,Pediatric Medicine PLLC,"4850 20, Otisco, NY",US,Pediatric Medicine PLLC,pediatric medicine pllc,pediatricmedicinepllc,"[pediatric, medicine, pllc]","4850 20, Otisco, NY",4850 20 otisco ny,485020otiscony,"[4850, 20, otisco, ny]","[4850, 20]"
1,S1-320151505,Fetech National Twin,"19034 Woodburn Road, Woodburn, IN",US,Fetech National Twin,fetech national twin,fetechnationaltwin,"[fetech, national, twin]","19034 Woodburn Road, Woodburn, IN",19034 woodburn road woodburn in,19034woodburnroadwoodburnin,"[19034, woodburn, road, woodburn, in]",[19034]
2,S1-938947364,General Design Innovations LLC,"7241 Osage Avenue, Mesa, AZ",US,General Design Innovations LLC,general design innovations llc,generaldesigninnovationsllc,"[general, design, innovations, llc]","7241 Osage Avenue, Mesa, AZ",7241 osage avenue mesa az,7241osageavenuemesaaz,"[7241, osage, avenue, mesa, az]",[7241]
3,S1-195839862,Construction Ideaz Papers Private Limited,"Building No.4/606, Prabhul Cottage Karimbalur,...",India,Construction Ideaz Papers Private Limited,construction ideaz papers private limited,constructionideazpapersprivatelimited,"[construction, ideaz, papers, private, limited]","Building No.4/606, Prabhul Cottage Karimbalur,...",building no 4 606 prabhul cottage karimbalur e...,buildingno4606prabhulcottagekarimbalurelakamon...,"[building, no, 4, 606, prabhul, cottage, karim...","[4, 606]"
4,S1-655046555,Penaloza and Bittle First Inc.,"4255 Charleswood Avenue, Memphis, TN",US,Penaloza and Bittle First Inc.,penaloza and bittle first inc,penalozaandbittlefirstinc,"[penaloza, and, bittle, first, inc]","4255 Charleswood Avenue, Memphis, TN",4255 charleswood avenue memphis tn,4255charleswoodavenuememphistn,"[4255, charleswood, avenue, memphis, tn]",[4255]

In [6]:
display(
    normalized_sample[
        [
            "entity_id",
            "name_raw",
            "name_norm",
            "name_compact",
            "name_tokens",
        ]
    ].head(30)
)

,entity_id,name_raw,name_norm,name_compact,name_tokens
0,S1-53356671,Pediatric Medicine PLLC,pediatric medicine pllc,pediatricmedicinepllc,"[pediatric, medicine, pllc]"
1,S1-320151505,Fetech National Twin,fetech national twin,fetechnationaltwin,"[fetech, national, twin]"
2,S1-938947364,General Design Innovations LLC,general design innovations llc,generaldesigninnovationsllc,"[general, design, innovations, llc]"
3,S1-195839862,Construction Ideaz Papers Private Limited,construction ideaz papers private limited,constructionideazpapersprivatelimited,"[construction, ideaz, papers, private, limited]"
4,S1-655046555,Penaloza and Bittle First Inc.,penaloza and bittle first inc,penalozaandbittlefirstinc,"[penaloza, and, bittle, first, inc]"
5,S1-758070915,National Investments LLC,national investments llc,nationalinvestmentsllc,"[national, investments, llc]"
6,S1-169338169,Reus Idaho Company,reus idaho company,reusidahocompany,"[reus, idaho, company]"
7,S1-796421498,Creative Projects Limited,creative projects limited,creativeprojectslimited,"[creative, projects, limited]"
8,S1-802535179,Goar Stone LLC,goar stone llc,goarstonellc,"[goar, stone, llc]"
9,S1-97176033,Lakshmi Consultants Private Limited,lakshmi consultants private limited,lakshmiconsultantsprivatelimited,"[lakshmi, consultants, private, limited]"
10,S1-983540069,Ss Technology Private Limited,ss technology private limited,sstechnologyprivatelimited,"[ss, technology, private, limited]"
11,S1-642488269,Rebbecca's Family Practice,rebbecca's family practice,rebbecca'sfamilypractice,"[rebbecca's, family, practice]"
12,S1-426953208,Heritage Society LLC,heritage society llc,heritagesocietyllc,"[heritage, society, llc]"
13,S1-818320211,Rozy Media Limited,rozy media limited,rozymedialimited,"[rozy, media, limited]"
14,S1-33984562,Slate PLLC,slate pllc,slatepllc,"[slate, pllc]"
15,S1-709960468,Apex Center,apex center,apexcenter,"[apex, center]"
16,S1-986840295,M 9 Certified Giant LLC,m 9 certified giant llc,m9certifiedgiantllc,"[m, 9, certified, giant, llc]"
17,S1-836296604,Coromandal Marketing Private Limited,coromandal marketing private limited,coromandalmarketingprivatelimited,"[coromandal, marketing, private, limited]"
18,S1-975412735,Preferred Business Systems Inc,preferred business systems inc,preferredbusinesssystemsinc,"[preferred, business, systems, inc]"
19,S1-739708548,Dream Investment Pvt Ltd,dream investment pvt ltd,dreaminvestmentpvtltd,"[dream, investment, pvt, ltd]"
20,S1-721469485,Primary Care Center of Staten Island Inc,primary care center of staten island inc,primarycarecenterofstatenislandinc,"[primary, care, center, of, staten, island, inc]"
21,S1-216733182,Spak Brothers,spak brothers,spakbrothers,"[spak, brothers]"
22,S1-369198632,Federman Chimera Associates,federman chimera associates,federmanchimeraassociates,"[federman, chimera, associates]"
23,S1-589302928,Munoz & Kaufman Inc,munoz kaufman inc,munozkaufmaninc,"[munoz, kaufman, inc]"
24,S1-527497541,Alpha Care Limited,alpha care limited,alphacarelimited,"[alpha, care, limited]"
25,S1-951433056,Dv College,dv college,dvcollege,"[dv, college]"
26,S1-857232066,Ayra Traders Pvt Ltd,ayra traders pvt ltd,ayratraderspvtltd,"[ayra, traders, pvt, ltd]"
27,S1-391683240,Patriot Tire Shop Group,patriot tire shop group,patriottireshopgroup,"[patriot, tire, shop, group]"
28,S1-630149953,Ss Construction Private Limited,ss construction private limited,ssconstructionprivatelimited,"[ss, construction, private, limited]"
29,S1-207329319,Dido Johnson Affiliated LLC,dido johnson affiliated llc,didojohnsonaffiliatedllc,"[dido, johnson, affiliated, llc]"

In [7]:
display(
    normalized_sample[
        [
            "entity_id",
            "address_raw",
            "address_norm",
            "address_compact",
            "address_tokens",
            "address_numbers",
        ]
    ].head(30)
)

,entity_id,address_raw,address_norm,address_compact,address_tokens,address_numbers
0,S1-53356671,"4850 20, Otisco, NY",4850 20 otisco ny,485020otiscony,"[4850, 20, otisco, ny]","[4850, 20]"
1,S1-320151505,"19034 Woodburn Road, Woodburn, IN",19034 woodburn road woodburn in,19034woodburnroadwoodburnin,"[19034, woodburn, road, woodburn, in]",[19034]
2,S1-938947364,"7241 Osage Avenue, Mesa, AZ",7241 osage avenue mesa az,7241osageavenuemesaaz,"[7241, osage, avenue, mesa, az]",[7241]
3,S1-195839862,"Building No.4/606, Prabhul Cottage Karimbalur,...",building no 4 606 prabhul cottage karimbalur e...,buildingno4606prabhulcottagekarimbalurelakamon...,"[building, no, 4, 606, prabhul, cottage, karim...","[4, 606]"
4,S1-655046555,"4255 Charleswood Avenue, Memphis, TN",4255 charleswood avenue memphis tn,4255charleswoodavenuememphistn,"[4255, charleswood, avenue, memphis, tn]",[4255]
5,S1-758070915,"1641 Virginia Lane, Hueytown, AL",1641 virginia lane hueytown al,1641virginialanehueytownal,"[1641, virginia, lane, hueytown, al]",[1641]
6,S1-169338169,"Sanford, ME, 31 Guillemette Street",sanford me 31 guillemette street,sanfordme31guillemettestreet,"[sanford, me, 31, guillemette, street]",[31]
7,S1-796421498,"12Thfloor, C, 1204, Roya Oasis, Jankalyan Naga...",12thfloor c 1204 roya oasis jankalyan nagarmal...,12thfloorc1204royaoasisjankalyannagarmalvaninr...,"[12thfloor, c, 1204, roya, oasis, jankalyan, n...","[12, 1204]"
8,S1-802535179,"2105 Wood Ridge Cove, Cedar Park, TX",2105 wood ridge cove cedar park tx,2105woodridgecovecedarparktx,"[2105, wood, ridge, cove, cedar, park, tx]",[2105]
9,S1-97176033,"A-301, New Sai Dham Chsl, Ramdev Park Road, Th...",a-301 new sai dham chsl ramdev park road thane...,a-301newsaidhamchslramdevparkroadthanemaharashtra,"[a-301, new, sai, dham, chsl, ramdev, park, ro...",[301]
10,S1-983540069,"Shop No. 1164, Pvt No.2, First Floor Kucha Mah...",shop no 1164 pvt no 2 first floor kucha mahaja...,shopno1164pvtno2firstfloorkuchamahajanichandni...,"[shop, no, 1164, pvt, no, 2, first, floor, kuc...","[1164, 2]"
11,S1-642488269,"2514 Messick Drive, Goshen, IN",2514 messick drive goshen in,2514messickdrivegoshenin,"[2514, messick, drive, goshen, in]",[2514]
12,S1-426953208,"139 Fort Graham Road, Whitney, TX",139 fort graham road whitney tx,139fortgrahamroadwhitneytx,"[139, fort, graham, road, whitney, tx]",[139]
13,S1-818320211,"Survey Number 127/P1, Opp, 66 Kv Ss, Varetha, ...",survey number 127 p1 opp 66 kv ss varetha mahe...,surveynumber127p1opp66kvssvarethamahesanakhera...,"[survey, number, 127, p1, opp, 66, kv, ss, var...","[127, 1, 66]"
14,S1-33984562,"735 Charlton Street, Southbridge, MA",735 charlton street southbridge ma,735charltonstreetsouthbridgema,"[735, charlton, street, southbridge, ma]",[735]
15,S1-709960468,"4 Hillside Court, Coxsackie, NY",4 hillside court coxsackie ny,4hillsidecourtcoxsackieny,"[4, hillside, court, coxsackie, ny]",[4]
16,S1-986840295,"4122 Scenic Drive, Dickinson, TX",4122 scenic drive dickinson tx,4122scenicdrivedickinsontx,"[4122, scenic, drive, dickinson, tx]",[4122]
17,S1-836296604,"G-3, Neel Madhav, Valji Ladha Cross Road, Near...",g-3 neel madhav valji ladha cross road near hi...,g-3neelmadhavvaljiladhacrossroadnearhieramongi...,"[g-3, neel, madhav, valji, ladha, cross, road,...",[3]
18,S1-975412735,"Loudoun County, 23355 Florina Court, VA",loudoun county 23355 florina court va,loudouncounty23355florinacourtva,"[loudoun, county, 23355, florina, court, va]",[23355]
19,S1-739708548,"2A, 2Nd Floor, Windcliffe, 50 D Peddar Road, C...",2a 2nd floor windcliffe 50 d peddar road cumba...,2a2ndfloorwindcliffe50dpeddarroadcumballahillm...,"[2a, 2nd, floor, windcliffe, 50, d, peddar, ro...","[2, 2, 50]"
20,S1-721469485,"130 Hunter Avenue, Staten Island, NY",130 hunter avenue staten island ny,130hunteravenuestatenislandny,"[130, hunter, avenue, staten, island, ny]",[130]
21,S1-216733182,"304/A, Shyamal Kunj 2, B/H Arya Shri, Opp Pent...",304 a shyamal kunj 2 b h arya shri opp pentago...,304ashyamalkunj2bharyashriopppentagonappartmen...,"[304, a, shyamal, kunj, 2, b, h, arya, shri, o...","[304, 2]"
22,S1-369198632,"Charlotte, 9214 Arbor Creek Drive, NC",charlotte 9214 arbor creek drive nc,charlotte9214arborcreekdrivenc,"[charlotte, 9214, arbor, creek, drive, nc]",[9214]
23,S1-589302928,"408 Hancock Street, Richmond City, VA",408 hancock street richmond city va,408hancockstreetrichmondcityva,"[408, hancock, street, richmond, city, va]",[408]
24,S1-527497541,"Maharashtra, A 204 Sawali Co Op Hsg Soc Plot 4...",maharashtra a 204 sawali co op hsg soc plot 41...,maharashtraa204sawalicoophsgsocplot41sec5kharg...,"[maharashtra, a, 204, sawali, co, op, hsg, soc...","[204, 41, 5]"
25,S1-951433056,"Shop No 408, Third Floor, Shopprix Mall, Secto...",shop no 408 third floor shopprix mall sector 5...,shopno408thirdfloorshopprixmallsector5ghaziaba...,"[shop, no, 408, third, floor, shopprix, mall, ...","[408, 5]"
26,S1-857232066,"No. 2-131, Gulbarga, Karnataka, Opp. Hasnapur ...",no 2-131 gulbarga karnataka opp hasnapur camp ...,no2-131gulbargakarnatakaopphasnapurcamppostdiv...,"[no, 2-131, gulbarga, karnataka, opp, hasnapur...","[2, 131]"
27,S1-391683240,"Patriot, OH, 280 Wright Road",patriot oh 280 wright road,patriotoh280wrightroad,"[patriot, oh, 280, wright, road]",[280]
28,S1-630149953,"Flat No. 904, 'A' Wing, Pristine Fontana Build...",flat no 904 'a' wing pristine fontana building...,flatno904'a'wingpristinefontanabuildingsno22be...,"[flat, no, 904, a, wing, pristine, fontana, bu...","[904, 22]"
29,S1-207329319,"12 Meeting House Lane, Unit 204, Scituate, MA",12 meeting house lane unit 204 scituate ma,12meetinghouselaneunit204scituatema,"[12, meeting, house, lane, unit, 204, scituate...","[12, 204]"

In [8]:
punctuation_examples = train_source1[
    train_source1["business_name"].str.contains(
        r"[.,&()/'-]",
        regex=True,
        na=False,
    )
].head(50)

punctuation_normalized = normalize_dataframe(
    punctuation_examples
)

display(
    punctuation_normalized[
        [
            "name_raw",
            "name_norm",
            "name_compact",
            "name_tokens",
        ]
    ]
)

,name_raw,name_norm,name_compact,name_tokens
0,Orelee's Barbershop,orelee's barbershop,orelee'sbarbershop,"[orelee's, barbershop]"
1,"Kelly Advisory, Inc",kelly advisory inc,kellyadvisoryinc,"[kelly, advisory, inc]"
2,Callicoat & Dailey Inc,callicoat dailey inc,callicoatdaileyinc,"[callicoat, dailey, inc]"
3,"Schaefer, Michael and Silver Associates",schaefer michael and silver associates,schaefermichaelandsilverassociates,"[schaefer, michael, and, silver, associates]"
4,"Aggie E. Nagle, L.C.S.W.",aggie e nagle l c s w,aggieenaglelcsw,"[aggie, e, nagle, l, c, s, w]"
5,Foot & Ankle Allied Center LLC,foot ankle allied center llc,footanklealliedcenterllc,"[foot, ankle, allied, center, llc]"
6,Joeann Hills Park Inc.,joeann hills park inc,joeannhillsparkinc,"[joeann, hills, park, inc]"
7,Primary Care Physicians Inc.,primary care physicians inc,primarycarephysiciansinc,"[primary, care, physicians, inc]"
8,Siobhan's Bike Shop LLC,siobhan's bike shop llc,siobhan'sbikeshopllc,"[siobhan's, bike, shop, llc]"
9,Foot & Ankle Patriot Group,foot ankle patriot group,footanklepatriotgroup,"[foot, ankle, patriot, group]"
10,Healthcare Janki Nutrition Pvt. Ltd.,healthcare janki nutrition pvt ltd,healthcarejankinutritionpvtltd,"[healthcare, janki, nutrition, pvt, ltd]"
11,Abhushan & Brothers Co,abhushan brothers co,abhushanbrothersco,"[abhushan, brothers, co]"
12,WG Harbor Worldwide P.C.,wg harbor worldwide p c,wgharborworldwidepc,"[wg, harbor, worldwide, p, c]"
13,Ear Nose & Throat Group of Oberlin,ear nose throat group of oberlin,earnosethroatgroupofoberlin,"[ear, nose, throat, group, of, oberlin]"
14,JPY Energy Pvt. Ltd.,jpy energy pvt ltd,jpyenergypvtltd,"[jpy, energy, pvt, ltd]"
15,Hartman & Hoang LLC,hartman hoang llc,hartmanhoangllc,"[hartman, hoang, llc]"
16,"Iraheta, Dacie, D.O.",iraheta dacie d o,irahetadaciedo,"[iraheta, dacie, d, o]"
17,"Pocius, Herrera & Lima Connecticut Inc",pocius herrera lima connecticut inc,pociusherreralimaconnecticutinc,"[pocius, herrera, lima, connecticut, inc]"
18,Murray & Cruz Inc,murray cruz inc,murraycruzinc,"[murray, cruz, inc]"
19,U Q & Z Kimco,u q z kimco,uqzkimco,"[u, q, z, kimco]"
20,"Mobley, Haislip & Barr Vision Center, LLC",mobley haislip barr vision center llc,mobleyhaislipbarrvisioncenterllc,"[mobley, haislip, barr, vision, center, llc]"
21,Osprey (India) Development LLP,osprey india development llp,ospreyindiadevelopmentllp,"[osprey, india, development, llp]"
22,"Adams, Williams and Alexander Carolina LLC",adams williams and alexander carolina llc,adamswilliamsandalexandercarolinallc,"[adams, williams, and, alexander, carolina, llc]"
23,"Knox and Nicholas, Inc",knox and nicholas inc,knoxandnicholasinc,"[knox, and, nicholas, inc]"
24,Doiron & Alvarez Token LLC,doiron alvarez token llc,doironalvareztokenllc,"[doiron, alvarez, token, llc]"
25,"Henson Worldwide, LLC",henson worldwide llc,hensonworldwidellc,"[henson, worldwide, llc]"
26,Panchavati Foods-Delhi,panchavati foods-delhi,panchavatifoods-delhi,"[panchavati, foods-delhi]"
27,Lafferty Certified Lifesciences Inc.,lafferty certified lifesciences inc,laffertycertifiedlifesciencesinc,"[lafferty, certified, lifesciences, inc]"
28,"Pediatric Prairie Physicians, LLC",pediatric prairie physicians llc,pediatricprairiephysiciansllc,"[pediatric, prairie, physicians, llc]"
29,Chong's Hospitality LLC,chong's hospitality llc,chong'shospitalityllc,"[chong's, hospitality, llc]"
30,"Bermudez, Rice and Crittenden Inc",bermudez rice and crittenden inc,bermudezriceandcrittendeninc,"[bermudez, rice, and, crittenden, inc]"
31,Louisa's Group,louisa's group,louisa'sgroup,"[louisa's, group]"
32,Hahn Pelican Inc.,hahn pelican inc,hahnpelicaninc,"[hahn, pelican, inc]"
33,"Val L. Roberts, MD",val l roberts md,vallrobertsmd,"[val, l, roberts, md]"
34,Bay Horse Inc.,bay horse inc,bayhorseinc,"[bay, horse, inc]"
35,Frederick's Machine Works,frederick's machine works,frederick'smachineworks,"[frederick's, machine, works]"
36,D & L Metro LLC,d l metro llc,dlmetrollc,"[d, l, metro, llc]"
37,"Allen, Sherpa & Lebowitz Superior LLC",allen sherpa lebowitz superior llc,allensherpalebowitzsuperiorllc,"[allen, sherpa, lebowitz, superior, llc]"
38,Kylie's Hair Studio,kylie's hair studio,kylie'shairstudio,"[kylie's, hair, studio]"
39,Fresh Certified Ashford-Leesburg,fresh certified ashford-leesburg,freshcertifiedashford-leesburg,"[fresh, certified, ashford-leesburg]"
40,I+ Corporate Inc.,i corporate inc,icorporateinc,"[i, corporate, inc]"
41,Namaskar & Co Company,namaskar co company,namaskarcocompany,"[namaskar, co, company]"
42,"Odessa York, CPA",odessa york cpa,odessayorkcpa,"[odessa, york, cpa]"
43,"Pediatric Dentistry Clinic, Inc",pediatric dentistry clinic inc,pediatricdentistryclinicinc,"[pediatric, dentistry, clinic, inc]"
44,Wiggins Molecular P.C.,wiggins molecular p c,wigginsmolecularpc,"[wiggins, molecular, p, c]"
45,"Ortega Kogyo, Inc",ortega kogyo inc,ortegakogyoinc,"[ortega, kogyo, inc]"
46,"Dasi Rothrock, DDS",dasi rothrock dds,dasirothrockdds,"[dasi, rothrock, dds]"
47,"Oliy Queenan, L.C.S.W.",oliy queenan l c s w,oliyqueenanlcsw,"[oliy, queenan, l, c, s, w]"
48,"Heavener Qdro, Inc",heavener qdro inc,heavenerqdroinc,"[heavener, qdro, inc]"
49,"Buttler, Wilding and Manjarrez Inc",buttler wilding and manjarrez inc,buttlerwildingandmanjarrezinc,"[buttler, wilding, and, manjarrez, inc]"

In [10]:
numeric_examples = train_source1[
    train_source1["business_address"].str.contains(
        r"\d",
        regex=True,
        na=False,
    )
].head(50)

numeric_normalized = normalize_dataframe(
    numeric_examples
)

display(
    numeric_normalized[
        [
            "address_raw",
            "address_norm",
            "address_numbers",
        ]
    ]
)

,address_raw,address_norm,address_numbers
0,"1795 Westchester Drive, High Point, NC",1795 westchester drive high point nc,[1795]
1,"17560 Ellis Road, Tahlequah, OK",17560 ellis road tahlequah ok,[17560]
2,"1712 Montebello Avenue, Phoenix, AZ",1712 montebello avenue phoenix az,[1712]
3,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",2100 cameron drive unit apartment g dundalk md,[2100]
4,"797, Lake Town Block A, Kolkata, Howrah, West ...",797 lake town block a kolkata howrah west bengal,[797]
5,"OH, Columbus, 5559 Orville Avenue",oh columbus 5559 orville avenue,[5559]
6,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",2505 tower 1 oakwood runwal greens mulund gore...,"[2505, 1]"
7,"1111 Church Street, Unit 2007, Nashville, TN",1111 church street unit 2007 nashville tn,"[1111, 2007]"
8,"337 Oakland Avenue, Michigan City, IN",337 oakland avenue michigan city in,[337]
9,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",294 meadowcreek drive unit unit 2 village of p...,"[294, 2]"
10,"11643 Prosperity Road, South Jordan, UT",11643 prosperity road south jordan ut,[11643]
11,"H.No.16-11-23/37/A, 2Nd Floor, Flat No.207, Sa...",h no 16-11-23 37 a 2nd floor flat no 207 sagar...,"[16, 11, 23, 37, 2, 207]"
12,"301 1st Street, Chokio, MN",301 1st street chokio mn,"[301, 1]"
13,"66 Edgewood Street, Bridgeport, CT",66 edgewood street bridgeport ct,[66]
14,"Unit BUILDING 3030, MD, 2701 Eastern Boulevard...",unit building 3030 md 2701 eastern boulevard m...,"[3030, 2701]"
15,"601 Oleander Circle, Virginia Beach City, VA",601 oleander circle virginia beach city va,[601]
16,"303, 3Rd Floor Sakar 5 B/H Natraj Cinema Ashra...",303 3rd floor sakar 5 b h natraj cinema ashram...,"[303, 3, 5]"
17,"Charlotte, NC, 833 Reliance Street",charlotte nc 833 reliance street,[833]
18,House No-777 Raghubir Bhawanmadan Pur Khadar S...,house no-777 raghubir bhawanmadan pur khadar s...,[777]
19,"Secunderabad, Hyderabad, Plot No.53, Flat No.4...",secunderabad hyderabad plot no 53 flat no 402 ...,"[53, 402, 53, 1]"
20,"Sapulpa, OK, 2204 Park Street",sapulpa ok 2204 park street,[2204]
21,"E-7, Second Floor, New Delhi, South Delhi, Delhi",e-7 second floor new delhi south delhi delhi,[7]
22,"4828 Hedges Avenue, Kansas City, MO",4828 hedges avenue kansas city mo,[4828]
23,"46/1106, Dhanalakshmi Road, Near Amani Auditor...",46 1106 dhanalakshmi road near amani auditoriu...,"[46, 1106]"
24,"32876 Circle Drive, Millsboro, DE",32876 circle drive millsboro de,[32876]
25,"5620 Trinity Road, Unit 103, Raleigh, NC",5620 trinity road unit 103 raleigh nc,"[5620, 103]"
26,"11900 54th Avenue, Plymouth, MN",11900 54th avenue plymouth mn,"[11900, 54]"
27,"Building No. 37/4, First Floor Opp Bharata Mat...",building no 37 4 first floor opp bharata mata ...,"[37, 4]"
28,"4024 39th Avenue, Seattle, WA",4024 39th avenue seattle wa,"[4024, 39]"
29,"4810 Nassau Avenue, Sand Springs, OK",4810 nassau avenue sand springs ok,[4810]
30,"126 D Street, Pittsfield, ME",126 d street pittsfield me,[126]
31,"#17/1, Lower Ground Floor, 1St Cross, Lalbagh ...",17 1 lower ground floor 1st cross lalbagh road...,"[17, 1, 1]"
32,"165 Linden Street, Unit 106, Wellesley, MA",165 linden street unit 106 wellesley ma,"[165, 106]"
33,"108 Richardson Street, Bethany, WV",108 richardson street bethany wv,[108]
34,"1216 Preston Avenue, Charlottesville City, VA",1216 preston avenue charlottesville city va,[1216]
35,"10101 Threave Road, Unit 301, Raleigh, NC",10101 threave road unit 301 raleigh nc,"[10101, 301]"
36,"C/O Dwarkadhis Enterprise, C.M. Palace, Ist Fl...",c o dwarkadhis enterprise c m palace ist floor...,[3]
37,"211 Dewey Road, IL, Rockton",211 dewey road il rockton,[211]
38,"53 Park Lane, Wellsville, NY",53 park lane wellsville ny,[53]
39,"74 429, Stockdale, TX",74 429 stockdale tx,"[74, 429]"
40,"2804, Tower A, Sarova, Samata Nagar, Kandivali...",2804 tower a sarova samata nagar kandivali eas...,[2804]
41,"Unit UNIT 367, 1400 Great Wolf Drive, WI, Vill...",unit unit 367 1400 great wolf drive wi village...,"[367, 1400]"
42,"1644 Crownsville Road, Fl 0, Crownsville, MD",1644 crownsville road fl 0 crownsville md,"[1644, 0]"
43,"House No.26-352, Kadavakollu Bhavanam, Bhuttai...",house no 26-352 kadavakollu bhavanam bhuttaipe...,"[26, 352]"
44,"325 Cross Street, Unit LOT 1A, Anderson, IN",325 cross street unit lot 1a anderson in,"[325, 1]"
45,"26 Stone Street, Unit 3, Beverly, MA",26 stone street unit 3 beverly ma,"[26, 3]"
46,"7196 State Route 14, Mcleansboro, IL",7196 state route 14 mcleansboro il,"[7196, 14]"
47,"12, Floor 2, Plot-750, 20, Satnam Nagar, Dr G ...",12 floor 2 plot-750 20 satnam nagar dr g d mar...,"[12, 2, 750, 20]"
48,"D No. 20-6-3/12, Dantuluri Vari Street, Ayodya...",d no 20-6-3 12 dantuluri vari street ayodyanag...,"[20, 6, 3, 12]"
49,"9889 Kent Street, Elk Grove, CA",9889 kent street elk grove ca,[9889]

In [11]:
train_source2 = read_source_file(
    TRAIN_DIR / "train_source2.tsv"
)

missing_address_examples = train_source2[
    train_source2["business_address"]
    .astype("string")
    .str.strip()
    .eq("")
].head(20)

missing_normalized = normalize_dataframe(
    missing_address_examples
)

display(
    missing_normalized[
        [
            "business_name",
            "address_raw",
            "address_norm",
            "address_tokens",
            "address_numbers",
        ]
    ]
)

,business_name,address_raw,address_norm,address_tokens,address_numbers
0,"Guerra And Krueger Table, LLC",,,[],[]
1,L E Pierce Cal [PC],,,[],[]
2,Preferred Bay Montage Inc,,,[],[]
3,DELONG STRATEGIC READY,,,[],[]
4,Desert Vanguard ([Maintenance]),,,[],[]
5,Wildlife Sóciety,,,[],[]
6,Orellana Kensington,,,[],[]
7,rathi holdings,,,[],[]
8,Berry Saul,,,[],[]
9,"Thrasher, Wanner 5tenson LLC Center",,,[],[]
10,Infinity Techno Private,,,[],[]
11,"Houghton, Nichols and Trosclair, LLC Service",,,[],[]
12,MURIAL FULTON STÁR LIVING L.L.C.,,,[],[]
13,Primary Care Associates Associates Center,,,[],[]
14,Hosakote Power,,,[],[]
15,3448 Sixth Ave,,,[],[]
16,DESIGN CONSTRUCTIONS PVT LTD.,,,[],[]
17,Shri Yashvardhan Educational Society,,,[],[]
18,"SNOWDEN LEGATO, LLC",,,[],[]
19,Troy Federation Youth,,,[],[]